apiVersion : apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: registry.localtest.com/product:1.1
          ports:
            - containerPort: 8184
      hostAliases:
      - ip: "20.194.18.209"
        hostnames:
        - "account.skcc.co.kr"
        - "apigateway.skcc.co.kr"
        - "bff.skcc.co.kr"
        - "cart.skcc.co.kr"
        - "order.skcc.co.kr"
        - "payment.skcc.co.kr"
        - "product.skcc.co.kr"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: product-ingress
spec:
  rules:
  - host: product.skcc.co.kr
    http:
      paths:
      - path: /
        backend:
          serviceName: product-svc
          servicePort: 8184

---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
  labels:
    app: product
spec:
  ports:
    - port: 8184
      targetPort: 8184
      name: product-svc
  selector:
    app: product
